### ISSUE TITLE
Cannot install fonts

### ISSUE THREAD

**Issue by diegohdez90** [braver/fonts#101]
I have problems to install fonts package in Atom.
How can I clean cache or bugs in Atom to fix?

Atom version: 1.51.0 x64
[Updated]
Installed today on Windows 10

Error image
![image](https://user-images.githubusercontent.com/10326623/94959708-3e8ebc00-04b7-11eb-8707-219b56a888ee.png)

Log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Diego\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Diego\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\Diego\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\Diego\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/fonts/versions/3.12.0/tarball',
1 verbose cli   '--target=5.0.13',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style',
1 verbose cli   '--msvs_version=2015' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose npm-session 2d2dd5395dd1fb37
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/braver/fonts/legacy.tar.gz/v3.12.0 3679ms (from cache)
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/fonts/versions/3.12.0/tarball zlib: unexpected end of file
9 timing stage:rollbackFailedOptional Completed in 6ms
10 timing stage:runTopLevelLifecycles Completed in 3765ms
11 verbose stack ZlibError: zlib: unexpected end of file
11 verbose stack     at Unzip.write (C:\Users\Diego\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:147:22)
11 verbose stack     at Unzip.flush (C:\Users\Diego\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:98:10)
11 verbose stack     at Unzip.end (C:\Users\Diego\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:104:10)
11 verbose stack     at Object.end (C:\Users\Diego\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\tar\lib\parse.js:421:21)
11 verbose stack     at PassThrough.onend (_stream_readable.js:672:10)
11 verbose stack     at Object.onceWrapper (events.js:286:20)
11 verbose stack     at PassThrough.emit (events.js:203:15)
11 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
12 verbose cwd C:\Users\Diego\AppData\Local\Temp\apm-install-dir-202092-15708-xfnidp.7ct7
13 verbose Windows_NT 10.0.18362
14 verbose argv "C:\\Users\\Diego\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Diego\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Diego\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Diego\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/fonts/versions/3.12.0/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style" "--msvs_version=2015"
15 verbose node v10.20.1
16 verbose npm  v6.14.5
17 error code Z_BUF_ERROR
18 error errno -5
19 error zlib: unexpected end of file
20 verbose exit [ -5, true ]

```

**Comment by lierdakil** [comment]
Hi. You're probably seeing a variation on https://github.com/braver/fonts/issues/97. TL;DR, most probably, node messed up, put a corrupted download in the download cache, and now silently refusing to re-download. [This comment](https://github.com/braver/fonts/issues/97#issuecomment-631479472) claims cleaning up `~/.atom/.apm` and `~/.atom/.npm`  fixed the issue. (`~/.atom` is `%userprofile%\.atom\` on Windows, i.e. `C:\Users\yourusername\.atom`)

**Comment by diegohdez90** [comment]
@lierdakil thank you very much. Only I have `~/.atom/.apm` directory. It works delete it.

**Comment by diegohdez90** [comment]
Issue fixed
